/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "test.v:1.1-9.10" *)
module test(a, b, y);
  (* src = "test.v:2.11-2.12" *)
  input a;
  wire a;
  (* src = "test.v:3.11-3.12" *)
  input b;
  wire b;
  (* src = "test.v:4.12-4.13" *)
  output y;
  wire y;
  assign y = a & (* src = "test.v:7.12-7.17" *) b;
endmodule
